parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandler:
            tags: [ 'app.command_handler' ]
        App\Shared\Domain\Bus\Query\QueryHandler:
            tags: [ 'app.query_handler' ]
        App\Shared\Domain\Bus\Event\DomainEventSubscriber:
            tags: [ 'app.domain_event_subscriber' ]
        App\Shared\Domain\Bus\Event\InMemoryDomainEventSubscriber:
            tags: [ 'app.in_memory_domain_event_subscriber' ]

    App\:
        resource: '../src/'

    App\Shared\Infrastructure\Bus\Event\InMemorySymfonyEventBus:
        arguments: [ !tagged_iterator app.in_memory_domain_event_subscriber ]
        lazy: true

    App\Shared\Infrastructure\Bus\Event\DomainEventMapping:
        arguments: [ !tagged_iterator app.domain_event_subscriber ]

    App\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
        arguments: [ !tagged_iterator app.command_handler ]

    App\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
        arguments: [ !tagged_iterator app.query_handler ]

    Doctrine\ORM\EntityManagerInterface:
        factory: [ App\Shared\Infrastructure\Persistence\Doctrine\EntityManagerFactory, create ]
        arguments:
            -   driver: '%env(MYSQL_DRIVER)%'
                host: '%env(MYSQL_HOST)%'
                port: '%env(MYSQL_PORT)%'
                dbname: '%env(MYSQL_DB)%'
                user: '%env(MYSQL_USER)%'
                password: '%env(MYSQL_PASSWORD)%'
            - '%env(APP_ENV)%'
        public: true

    App\Shared\Domain\Bus\Event\EventBus $syncBus: '@App\Shared\Infrastructure\Bus\Event\InMemorySymfonyEventBus'
